menu:
  Archive: /archives

logo: Michael Kohler

more:
  Github: https://github.com/MichaelKohler
  CV: https://mkohler.codes
  Reps: https://reps.mozilla.org/u/michaelkohler

about:
  title:
  link:

disqus_shortname:

excerpt_num: 120

footer_info:
